# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BartenderUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from menuOptions import Ui_MenuWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 811)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.viewMenu = QtWidgets.QPushButton(self.centralwidget)
        self.viewMenu.setGeometry(QtCore.QRect(20, 620, 189, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.viewMenu.setFont(font)
        self.viewMenu.setAutoFillBackground(False)
        self.viewMenu.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.viewMenu.setObjectName("viewMenu")

        self.logoName = QtWidgets.QLabel(self.centralwidget)
        self.logoName.setGeometry(QtCore.QRect(20, 0, 1021, 191))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(72)
        self.logoName.setFont(font)
        self.logoName.setAutoFillBackground(False)
        self.logoName.setStyleSheet("")
        self.logoName.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logoName.setTextFormat(QtCore.Qt.RichText)
        self.logoName.setObjectName("logoName")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1041, 771))
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("BartenderLogo.png"))
        self.label.setObjectName("label")
        self.logoNameBackground = QtWidgets.QLabel(self.centralwidget)
        self.logoNameBackground.setGeometry(QtCore.QRect(30, 0, 1021, 191))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(72)
        self.logoNameBackground.setFont(font)
        self.logoNameBackground.setAutoFillBackground(False)
        self.logoNameBackground.setStyleSheet("")
        self.logoNameBackground.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logoNameBackground.setTextFormat(QtCore.Qt.RichText)
        self.logoNameBackground.setObjectName("logoNameBackground")
        self.label.raise_()
        self.viewMenu.raise_()
        self.logoName.raise_()
        self.logoNameBackground.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_Drink = QtWidgets.QAction(MainWindow)
        self.actionAdd_Drink.setObjectName("actionAdd_Drink")
        self.actionRemove_Drink = QtWidgets.QAction(MainWindow)
        self.actionRemove_Drink.setObjectName("actionRemove_Drink")
        self.menuFile.addAction(self.actionAdd_Drink)
        self.menuFile.addAction(self.actionRemove_Drink)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.viewMenu.setText(_translate("MainWindow", "View Menu"))
        self.viewMenu.clicked.connect(self.open_menu_window)
        self.logoName.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color: solid black; border: 2px solid black;\">Autonomous Bartender</span></p></body></html>\n"
""))
        self.logoNameBackground.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"color:#ff5500; border: 2px solid black;\">Autonomous Bartender</span></p></body></html>\n"
""))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAdd_Drink.setText(_translate("MainWindow", "Add Drink"))
        self.actionRemove_Drink.setText(_translate("MainWindow", "Remove Drink"))


    def open_menu_window(self):
        self.menuWindow = QtWidgets.QMainWindow()
        self.menuUi = Ui_MenuWindow()
        self.menuUi.setupUi(self.menuWindow)
        self.menuWindow.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
