# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuOptions.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json


class Ui_MenuWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(800, 600)
        MenuWindow.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.centralwidget = QtWidgets.QWidget(MenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menuOptions = QtWidgets.QListWidget(self.centralwidget)
        self.menuOptions.setGeometry(QtCore.QRect(100, 110, 600, 400))
        self.menuOptions.setObjectName("menuOptions")
        font = QtGui.QFont()
        font.setPointSize(32)  # Adjust the desired font size
        self.menuOptions.setFont(font)
        self.pourButton = QtWidgets.QPushButton(self.centralwidget)
        self.pourButton.setGeometry(QtCore.QRect(150, 520, 150, 40))
        self.pourButton.setObjectName("pourButton")
        self.pourButton.setText("Pour Drink")
        self.customizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.customizeButton.setGeometry(QtCore.QRect(500, 520, 150, 40))
        self.customizeButton.setObjectName("customizeButton")
        self.customizeButton.setText("Customize")
        MenuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MenuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MenuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MenuWindow)
        self.statusbar.setObjectName("statusbar")
        MenuWindow.setStatusBar(self.statusbar)
        self.load_drinks_from_json()

        self.retranslateUi(MenuWindow)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "MainWindow"))

    def load_drinks_from_json(self):
        with open('drinks.json') as file:
            drinks_data = json.load(file)
    
    # Sort the drinks_data list by name
        drinks_data.sort(key=lambda x: x['name'])

        for drink in drinks_data:
            drink_name = drink['name']
            self.menuOptions.addItem(drink_name)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuWindow = QtWidgets.QMainWindow()
    ui = Ui_MenuWindow()
    ui.setupUi(MenuWindow)
    MenuWindow.show()
    sys.exit(app.exec_())
